language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t carlylee/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true carlylee/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-ap-northeast-2-674089888659"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
