language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t carlylee/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true carlylee/docker-react npm run test
